In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
Data = pd.read_csv('data.csv',sep=",")

In [3]:
Data

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [4]:
import os
os.getcwd()

'C:\\Users\\PC\\Documents'

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
Data = pd.read_csv('avito_car_dataset_ALL.csv',sep=",", encoding='latin-1')

In [7]:
Data

Unnamed: 0                                               Lien  \
0               0  https://www.avito.ma/fr/massira_2/voitures/FIA...   
1               1  https://www.avito.ma/fr/temara/voitures/Dacia_...   
2               2  https://www.avito.ma/fr/casablanca/voitures/Da...   
3               3  https://www.avito.ma/fr/casablanca/voitures/to...   
4               4  https://www.avito.ma/fr/dakhla/voitures/Toyota...   
...           ...                                                ...   
24765       24771  https://www.avito.ma/fr/gueliz/voitures/Mini_C...   
24766       24772  https://www.avito.ma/fr/safi/voitures/mini_coo...   
24767       24773  https://www.avito.ma/fr/sal%C3%A9/voitures/Min...   
24768       24774  https://www.avito.ma/fr/polo/voitures/Mini_coo...   
24769       24775  https://www.avito.ma/fr/marrakech/voitures/min...   

            Ville    Secteur      Marque      Modèle  Année-Modèle  \
0          Temara  Massira 2        Fiat       Punto          2007   
1          Temara        NaN       Dacia  Dokker Van          2013   
2      Casablanca        NaN       Dacia      Dokker          2014   
3      Casablanca        NaN  Volkswagen     Touareg          2005   
4          Dakhla        NaN      Toyota       Prado          2007   
...           ...        ...         ...         ...           ...   
24765   Marrakech     Guéliz        mini      cabrio          2011   
24766        Safi        NaN        mini      cooper          2007   
24767        Salé        NaN        mini         one          2006   
24768  Casablanca       Polo        mini      cooper          2010   
24769   Marrakech        NaN        mini      cooper          2008   

             Kilométrage Type de carburant  Puissance fiscale  ...  \
0      200 000 - 249 999            Diesel                  5  ...   
1      400 000 - 449 999            Diesel                  6  ...   
2      160 000 - 169 999            Diesel                  6  ...   
3              0 - 4 999            Diesel                 10  ...   
4      200 000 - 249 999            Diesel                 12  ...   
...                  ...               ...                ...  ...   
24765    70 000 - 74 999           Essence                  9  ...   
24766  190 000 - 199 999           Essence                  9  ...   
24767    10 000 - 14 999           Essence                  8  ...   
24768  140 000 - 149 999           Essence                  9  ...   
24769  180 000 - 189 999           Essence                  9  ...   

      Caméra de recul  Vitres électriques    ABS    ESP Régulateur de vitesse  \
0               False               False   True  False                 False   
1               False               False  False  False                 False   
2               False               False  False  False                 False   
3               False               False  False  False                 False   
4               False               False   True  False                 False   
...               ...                 ...    ...    ...                   ...   
24765           False               False   True   True                 False   
24766           False               False   True   True                 False   
24767           False               False   True  False                 False   
24768           False               False   True   True                 False   
24769           False               False  False  False                 False   

       Limiteur de vitesse  CD/MP3/Bluetooth  Ordinateur de bord  \
0                    False              True               False   
1                    False             False               False   
2                    False             False               False   
3                    False             False               False   
4                    False              True               False   
...                    ...               ...                 ...   
24765      

In [8]:
X = Data.iloc[:,2:-1]
Y = Data.iloc[:,-1]

In [9]:
X

Ville    Secteur      Marque      Modèle  Année-Modèle  \
0          Temara  Massira 2        Fiat       Punto          2007   
1          Temara        NaN       Dacia  Dokker Van          2013   
2      Casablanca        NaN       Dacia      Dokker          2014   
3      Casablanca        NaN  Volkswagen     Touareg          2005   
4          Dakhla        NaN      Toyota       Prado          2007   
...           ...        ...         ...         ...           ...   
24765   Marrakech     Guéliz        mini      cabrio          2011   
24766        Safi        NaN        mini      cooper          2007   
24767        Salé        NaN        mini         one          2006   
24768  Casablanca       Polo        mini      cooper          2010   
24769   Marrakech        NaN        mini      cooper          2008   

             Kilométrage Type de carburant  Puissance fiscale  \
0      200 000 - 249 999            Diesel                  5   
1      400 000 - 449 999            Diesel                  6   
2      160 000 - 169 999            Diesel                  6   
3              0 - 4 999            Diesel                 10   
4      200 000 - 249 999            Diesel                 12   
...                  ...               ...                ...   
24765    70 000 - 74 999           Essence                  9   
24766  190 000 - 199 999           Essence                  9   
24767    10 000 - 14 999           Essence                  8   
24768  140 000 - 149 999           Essence                  9   
24769  180 000 - 189 999           Essence                  9   

      Boite de vitesses  Nombre de portes  ... Radar de recul Caméra de recul  \
0              Manuelle               5.0  ...          False           False   
1              Manuelle               3.0  ...          False           False   
2              Manuelle               5.0  ...          False           False   
3           Automatique               5.0  ...          False           False   
4              Manuelle               5.0  ...          False           False   
...                 ...               ...  ...            ...             ...   
24765          Manuelle               3.0  ...          False           False   
24766          Manuelle               3.0  ...          False           False   
24767          Manuelle               3.0  ...          False           False   
24768       Automatique               3.0  ...          False           False   
24769          Manuelle               NaN  ...          False           False   

      Vitres électriques    ABS    ESP  Régulateur de vitesse  \
0                  False   True  False                  False   
1                  False  False  False                  False   
2                  False  False  False                  False   
3                  False  False  False                  False   
4                  False   True  False                  False   
...                  ...    ...    ...                    ...   
24765              False   True   True                  False   
24766              False   True   True                  False   
24767              False   True  False                  False   
24768              False   True   True                  False   
24769              False  False  False                  False   

       Limiteur de vitesse  CD/MP3/Bluetooth  Ordinateur de bord  \
0                    False              True               False   
1                    False             False               False   
2                    False             False               False   
3                    False             False               False   
4                    False              True               False   
...                    ...               ...                 ...   
24765                False             False               False   
24766                False              True               False   
24767                Fal

In [10]:
Y

0         60000
1         70000
2         90000
3         90000
4         97000
          ...  
24765    180000
24766     63000
24767     60000
24768     85000
24769     84000
Name: Prix, Length: 24770, dtype: int64

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Ville",OneHotEncoder(sparse=False),[0])],remainder = 'passthrough')
X = ct.fit_transform(X)

In [15]:
X

array([[0.0, 0.0, 0.0, ..., True, False, False],
       [0.0, 0.0, 0.0, ..., False, False, False],
       [0.0, 0.0, 0.0, ..., False, False, False],
       ...,
       [0.0, 0.0, 0.0, ..., True, False, False],
       [0.0, 0.0, 0.0, ..., True, False, False],
       [0.0, 0.0, 0.0, ..., False, False, False]], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Secteur",OneHotEncoder(sparse=False),[1]),("Marque",OneHotEncoder(sparse=False),[2])],remainder = 'passthrough')
X = ct.fit_transform(X)

In [17]:
X

array([[1.0, 0.0, 1.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., False, False, False],
       [1.0, 0.0, 1.0, ..., False, False, False],
       ...,
       [1.0, 0.0, 1.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., False, False, False]], dtype=object)

AttributeError: 'numpy.ndarray' object has no attribute 'Secteur'

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Modèle",OneHotEncoder(sparse=False),[3]),
                        ("Type de carburant",OneHotEncoder(sparse=False),[6])],
                        remainder = 'passthrough')
X = ct.fit_transform(X)

In [20]:
X

array([[1.0, 0.0, 1.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., False, False, False],
       [1.0, 0.0, 1.0, ..., False, False, False],
       ...,
       [1.0, 0.0, 1.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., False, False, False]], dtype=object)

In [36]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Boite de vitesses",OneHotEncoder(sparse=False),[8]),
                        ("Origine",OneHotEncoder(sparse=False),[10]),
                        ("Première main",OneHotEncoder(sparse=False),[11]),
                        ("État",OneHotEncoder(sparse=False),[12]),
                        ("Jantes aluminium",OneHotEncoder(sparse=False),[13]),
                        ("Airbags",OneHotEncoder(sparse=False),[14]),
                        ("Climatisation",OneHotEncoder(sparse=False),[15]),
                        ("Système de navigation/GPS",OneHotEncoder(sparse=False),[16]),
                        ("Toit ouvrant",OneHotEncoder(sparse=False),[17]),
                        ("Sièges cuir",OneHotEncoder(sparse=False),[18]),
                       ("Radar de recul",OneHotEncoder(sparse=False),[19]),
                        ("Caméra de recul",OneHotEncoder(sparse=False),[20]),
                        ("Vitres électriques",OneHotEncoder(sparse=False),[21]),
                        ("ABS",OneHotEncoder(sparse=False),[22]),
                       ("ESP",OneHotEncoder(sparse=False),[23]),
                       ("Régulateur de vitesse",OneHotEncoder(sparse=False),[24]),
                       ("Limiteur de vitesse",OneHotEncoder(sparse=False),[25]),
                       ("CD/MP3/Bluetooth",OneHotEncoder(sparse=False),[26]),
                       ("Ordinateur de bord",OneHotEncoder(sparse=False),[27]),
                       ("Verrouillage centralisé à distance",OneHotEncoder(sparse=False),[28])],remainder = 'passthrough')
X = ct.fit_transform(X)

In [41]:
X[[0]]

array([[1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0,
        1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0,
        0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct1 = ColumnTransformer([("Marque",OneHotEncoder(),[2])],remainder = 'passthrough')
X = ct1.fit_transform(X)

In [46]:
X[[0]]

array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0,
        0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0,
        1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [26]:
X[8][7]

0.0

In [27]:
X[27][27]

0.0

In [32]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)

In [33]:
X_train

array([[0.0, 1.0, 0.0, ..., True, False, False],
       [0.0, 1.0, 0.0, ..., False, False, False],
       [0.0, 1.0, 0.0, ..., True, False, False],
       ...,
       [0.0, 1.0, 0.0, ..., True, False, False],
       [0.0, 1.0, 0.0, ..., True, False, False],
       [0.0, 1.0, 0.0, ..., True, False, False]], dtype=object)

In [34]:
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

ValueError: could not convert string to float: 'Mercedes-Benz'

In [47]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct1 = ColumnTransformer([("Marque",OneHotEncoder(),[2])],remainder = 'passthrough')
X = ct1.fit_transform(X)

In [48]:
X[[0]]

array([[1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0,
        1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,
        1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0,
        1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [49]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct1 = ColumnTransformer([("Marque",OneHotEncoder(),[263])],remainder = 'passthrough')
X = ct1.fit_transform(X)

In [50]:
X[[0]]

array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0